name: Deploy Firebase Functions
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
        working-directory: functions
      - run: npm run build
        working-directory: functions
        continue-on-error: true
      - run: npm install -g firebase-tools
      - run: firebase deploy --only functions --project ${{ vars.PRD_PROJECT_ID }}
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.PRD_FIREBASE_SERVICE_ACCOUNT }}
