name: deploy production functions on tag (release)
on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: "functions"
jobs:
  deploy_functions_prod:
    env:
      FIREBASE_TOOLS_VERSION: "12.4.8"
      GOOGLE_APPLICATION_CREDENTIALS: ${{ vars.GOOGLE_APPLICATION_CREDENTIALS }}
      GCLOUD_SERVICE_KEY: ${{ secrets.PROD_GCP_SA_KEY }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
          cache-dependency-path: "functions/package-lock.json"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ vars.PROD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.PROD_SERVICE_ACCOUNT }}
          create_credentials_file: true
          export_environment_variables: true

      - name: make GOOGLE_APPLICATION_CREDENTIALS
        run: echo $GCLOUD_SERVICE_KEY > $GOOGLE_APPLICATION_CREDENTIALS

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@${FIREBASE_TOOLS_VERSION}

      - name: Install Dependencies
        run: npm install
        working-directory: ./functions

      - name: Deploy to Firebase
        run: firebase -P production deploy --only functions --force
